### ISSUE TITLE
Low hanging fruits for editable ELAN

### ISSUE THREAD

**Issue by letuananh** [neocl/speach#20]
- Change participant codes
- Change tier names
- Change annotation texts
- Delete annotations

**Comment by letuananh** [comment]
These three are done with pull request https://github.com/neocl/speach/pull/21

- Change participant codes
- Change tier names
- Change annotation texts

@vicchuayh I didn't update the documentation yet, but you can see sample code in this test case (line 133, 137, and 142):
https://github.com/neocl/speach/blob/e289f66b8110665abd92625b6432d64652f32045/test/test_elan.py#L118

Deleting annotations is tricky. We can save that for later. If you encounter any issue, please fire an issue in milestone [ELAN edit (here)](https://github.com/neocl/speach/milestone/2)

**Comment by vicchuayh** [comment]
Bug found where running the following code

def edit_elan(filepath):
    eaf = elan.read_eaf(filepath) 
    for tier in eaf:
        if "001" in tier.participant: #== "P001"
            tier.participant = tier.participant.replace("001", "x")
            eaf.save('C:/Users/victoria/Desktop/renaming_codes/cipher/test_2_renamed.eaf')
            print("001", tier.participant, tier.name)
        else:
            print("%s not found in %s, %s" % ("001", tier.participant, tier.name))
edit_elan(file)`

gives an error where tier.participant in some tiers are renamed correctly, but are not (see test_2_renamed.eaf). The print output shows that the substring can be successfully located and replaced in tier.participant (see output_test_2.txt) but the saved file does not reflect that. 

[eaf_files.zip](https://github.com/neocl/speach/files/6519980/eaf_files.zip)
[output_test_2.txt](https://github.com/neocl/speach/files/6519981/output_test_2.txt)

**Comment by letuananh** [comment]
Thank you @vicchuayh  I'll look into this asap

**Comment by letuananh** [comment]
@vicchuayh what you found was indeed a bug. I already pushed the fix to upstream [neocl/speach](https://github.com/neocl/speach). It's ready to be tested again. Thank you.
