### ISSUE TITLE
Add function to trim audio file by annotation timestamps

### ISSUE THREAD

**Issue by vicchuayh** [neocl/speach#5]
Provide audio trimming capabilities based on user-defined annotations:

- Ideally accurate to milliseconds
- Based on open-source audio pipelines (ffmpeg)
- Outputs trimmed audio file in chunks or 1 concatenated file

**Comment by letuananh** [comment]
https://github.com/neocl/speach/issues/10

**Comment by letuananh** [comment]
Hi @vicchuayh Can you elaborate on this function

>  Outputs trimmed audio file in chunks or 1 concatenated file
